<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZjOIDBp\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZjOIDBp/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerZjOIDBp.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerZjOIDBp\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerZjOIDBp\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'ZjOIDBp',
    'container.build_id' => 'c3cc08b9',
    'container.build_time' => 1516027754,
));
